@baseUrl = http://localhost:4000/api/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg5MTYyMTcxLCJleHAiOjE3ODkxNjMwNzF9.gAeb4lzdOeyiDjmNI-6kJZ6VvvCvaHcHo9ULFnfx4rs

### health check
GET http://localhost:4000/health

### sign up
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
    "name": "Ibenne John",
    "email": "ibennejohn0@gmail.com",
    "password": "1111"
}

### sign in
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "ibennejohn3@gmail.com",
    "password": "1111"
}

### refresh Token
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "265777c51cdb8083d28b9d9c1006565cfb808470934529cf5e8dcd8cbece31576f29544484b3cfa0c8e5d11d6e"
}

### refresh Token
DELETE  {{baseUrl}}/auth/logout/50092110b15c06628b0fd38baa34f52c871e575b911dfdcaf66a939290bb265779889ee66a63e4b028fb82b833

### post budget
POST {{baseUrl}}/budgets
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "2 week budget",
    "income": 40000,
    "end_date": "2026-09-14"
}

### get all budgets
GET {{baseUrl}}/budgets
Authorization: Bearer {{accessToken}}

### get budget
GET {{baseUrl}}/budgets/4
Authorization: Bearer {{accessToken}}