@baseUrl = http://localhost:4000/api/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg5NjgwMjgzLCJleHAiOjE3ODk2ODExODN9.KfmkhNEweiWPHw8Oo3djw9VchTzJMk5AWGUdStkaZS4


### health check
GET http://localhost:4000/health

### sign up
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
    "name": "joe",
    "email": "ibennejohn3@gmail.com",
    "password": "1111"
}

### sign in
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "ibennejohn3@gmail.com",
    "password": "1111"
}

### refresh Token
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "265777c51cdb8083d28b9d9c1006565cfb808470934529cf5e8dcd8cbece31576f29544484b3cfa0c8e5d11d6e"
}

### refresh Token
DELETE  {{baseUrl}}/auth/logout/50092110b15c06628b0fd38baa34f52c871e575b911dfdcaf66a939290bb265779889ee66a63e4b028fb82b833

### post budget
POST {{baseUrl}}/budgets
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "100 week budget",
    "income": 40000,
    "end_date": "2026-09-24"
}

### get all budgets
GET {{baseUrl}}/budgets
Authorization: Bearer {{accessToken}}

### get budget
GET {{baseUrl}}/budgets/4
Authorization: Bearer {{accessToken}}

### create category
POST {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "budgetId": 3,
    "name": "eletricity"
}

### get all categories
GET {{baseUrl}}/categories/3
Authorization: Bearer {{accessToken}}


### get all categories
POST {{baseUrl}}/expenses
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "expenses": [
        {
            "budgetId": 10,
            "categoryId": 5,
            "name": "1 book",
            "amount": 3000
        },
        {
            "budgetId": 10,
            "categoryId": 5,
            "name": "2 book",
            "amount": 3000
        },
        {
            "budgetId": 10,
            "categoryId": 5,
            "name": "3 book",
            "amount": 3000
        },
        {
            "budgetId": 10,
            "categoryId": 5,
            "name": "4 book",
            "amount": 3000
        },
        {
            "budgetId": 10,
            "categoryId": 5,
            "name": "5 book",
            "amount": 3000
        },
        {
            "budgetId": 10,
            "categoryId": 5,
            "name": "6 book",
            "amount": 3000
        }
    ]
}


### get all categories
GET {{baseUrl}}/expenses/10
Authorization: Bearer {{accessToken}}

### create transaction
POST {{baseUrl}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "budgetId": 2,
    "categoryId": 6,
    "amount": 5000
}

### list all transactions by budget id and filter by category id or data
GET {{baseUrl}}/transactions/5?categoryId=6&date=2026-09-16
Authorization: Bearer {{accessToken}}

### get the daily summary
GET {{baseUrl}}/dailySummaries/10
Authorization: Bearer {{accessToken}}