CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(10) NOT NULL,
    email VARCHAR(10) NOT NULL UNIQUE,
    phone_number VARCHAR(10) NOT NULL UNIQUE,
    role VARCHAR(10) NOT NULL DEFAULT "USER" CHECK (role IN ("USER", "ADMIN"))
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    update_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

